#!/usr/bin/env bash
# Script Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ./1-install_nginx_web_server

new_string="_;\\n\\trewrite\\ ^\/redirect_me http://www.example.com permanent;\\n"

sudo sed -i "s/_;/$new_string/" /etc/nginx/sites-available/default

sudo service nginx restart
